Fix/node edge ane 328
fossas/fossa-cli pull request #1075
Opened 2022-10-14 06:38 UTC by meghfossa

# Overview

_Provide an overview of this change. Describe the intent of this change, and how it implements that intent._

_Example: This PR accomplishes X by doing Y._

## Acceptance criteria

_If this PR is successful, what impact does it have on the user experience?_

_Example: When users do X, Y should now happen._

## Testing plan

_How did you validate that this PR works? What literal steps did you take when manually checking that your code works?_

_Example:_

1. _Set up test case X._
2. _Run command Y. Make sure Z happens._

_This section should list concrete steps that a reviewer can sanity check and repeat on their own machine (and provide any needed test cases)._

## Risks

_Highlight any areas that you're unsure of, want feedback on, or want reviewers to pay particular attention to._

_Example: I'm not sure I did X correctly, can reviewers please double-check that for me?_

## References

_Add links to any referenced GitHub issues, Zendesk tickets, Jira tickets, Slack threads, etc._

_Example:_

- _[ANE-123](https://fossa.atlassian.net/browse/ANE-123): Implement X._

## Checklist

- [ ] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).

2022-10-14 07:01 UTC, meghfossa commented on src/Strategy/Node/Npm/PackageLock.hs
> -      -- Add edge from parent
We would want to capture dependencies only in the `requires` block, but this made it such that edges were created between `dependencies`'s children. This is still a spooky change!

2022-10-17 18:28 UTC, csasarak requested changes
I just left a couple questions.

2022-10-17 18:33 UTC, csasarak approved these changes

2022-10-17 23:24 UTC, meghfossa commented on src/Strategy/Node/Npm/PackageLock.hs
> +      traverseWithKey' (maybeAddDep False) packageDeps
I decided to keep the current code, mainly as I found it easier to read/reason with `traverseWithKey'` in lockfile v2 graph traversal.

2022-10-17 23:54 UTC, merged