Feat/adds conan 3
fossas/fossa-cli pull request #1229
Opened 2023-06-16 16:42 UTC by meghfossa

# Overview

_Provide an overview of this change. Describe the intent of this change, and how it implements that intent._

_Example: This PR accomplishes X by doing Y._

## Acceptance criteria

_If this PR is successful, what impact does it have on the user experience?_

_Example: When users do X, Y should now happen._

## Testing plan

_How did you validate that this PR works? What literal steps did you take when manually checking that your code works?_

_Example:_

1. _Set up test case X._
2. _Run command Y. Make sure Z happens._

_This section should list concrete steps that a reviewer can sanity check and repeat on their own machine (and provide any needed test cases)._

## Risks

_Highlight any areas that you're unsure of, want feedback on, or want reviewers to pay particular attention to._

_Example: I'm not sure I did X correctly, can reviewers please double-check that for me?_

## Metrics

_Is this change something that can or should be tracked? If so, can we do it today? And how? If its easy, do it_

## References

_Add links to any referenced GitHub issues, Zendesk tickets, Jira tickets, Slack threads, etc._

_Example:_

- _[ANE-123](https://fossa.atlassian.net/browse/ANE-123): Implement X._

## Checklist

- [ ] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).

2023-06-16 17:26 UTC, meghfossa commented on src/Graphing/Enrich.hs
> +      archiveLocators <-
Ideally, we do something where `licenseScanSourceUnit` provides `(vendorDep, locator)s` so, even if we do not have version in our dependency, we can confidently perform replacement in the graph. I left it in this implementation, as we always have revision value, and more so unique hash in this revision for conan.

2023-06-16 17:28 UTC, meghfossa commented on src/Graphing/Enrich.hs
> +-- * TODO: Ignore non-production dependency in transformation
I will address this in PR which adds analyzer, and discovery for conan.

2023-06-16 17:30 UTC, meghfossa commented
@spatten tagged you here since you did all other conan pr reviews

2023-06-16 23:58 UTC, spatten requested changes
Requesting changes because I think we should support the `FullFileUploads` flag for sure. All other comments are optional

2023-06-16 23:58 UTC, spatten commented on src/Graphing/Enrich.hs
> +          SkippingNotSupported
I'm reading this as "in practice we often get code changes without a change in the version of the dependency"? If so, then yeah, this makes total sense.

2023-06-16 23:58 UTC, spatten commented on src/Graphing/Enrich.hs
> +          (FullFileUploads False)
I think we should respect the org's settings on this. This is pretty important to some orgs

2023-06-16 23:58 UTC, spatten commented on src/Graphing/Enrich.hs
> +          SkippingNotSupported
If, however, we're using the hash of the contents to get the version, then I think enabling skipping would be a nice performance boost for basically free

2023-06-16 23:58 UTC, spatten commented on src/Graphing/Enrich.hs
> +module Graphing.Enrich (
I think this should be called something like `Graphing.EnrichConan`. `Graphing.Enrich` seems too generic, considering that all of these functions are specific to Conan.

2023-06-16 23:58 UTC, spatten commented on src/Graphing/Enrich.hs
> +conanDepToVendorDep :: Dependency -> Either Dependency (Dependency, VendoredDependency)
I think the behaviour of `conanToVendoredDep`, `locatorToArchiveDep` and `findArchiveTwin` is just complicated enough that we should have either unit tests for them or tests for the unhappy path of `conanToArchives` that shows that they return a `Left` result when we expect them to

2023-06-20 15:15 UTC, csasarak approved these changes
I agree with Scott on changes, but will approve since he's already requested them. Everything I mention is optional.

2023-06-20 15:15 UTC, csasarak commented on src/Graphing/Enrich.hs
> +    archiveToConanDep :: [Dependency] -> Either [Dependency] [(Dependency, Dependency)]
[Optional] My understanding here is that the `Left` side of the `Either` is a list of deps with no partner. If that's true I'd recommend making a small newtype to describe the difference:

```haskell
newtype LonelyDeps = LonelyDeps  { unLonelyDeps :: [Dependency] }
  deriving (Eq, Ord)
  deriving newtype (Show) 
```

I think this replacement should only need a few calls to the constructor and `unLonelyDeps` in this module to work.

2023-07-06 00:35 UTC, spatten approved these changes
This all looks great!

2023-07-07 01:44 UTC, merged