Ane 1164 show lernie results in scan results
fossas/fossa-cli pull request #1269
Opened 2023-09-01 23:03 UTC by spatten

# Overview

_Provide an overview of this change. Describe the intent of this change, and how it implements that intent._

_Example: This PR accomplishes X by doing Y._

## Acceptance criteria

_If this PR is successful, what impact does it have on the user experience?_

_Example: When users do X, Y should now happen._

## Testing plan

_How did you validate that this PR works? What literal steps did you take when manually checking that your code works?_

_Example:_

1. _Set up test case X._
2. _Run command Y. Make sure Z happens._

_This section should list concrete steps that a reviewer can sanity check and repeat on their own machine (and provide any needed test cases)._

## Risks

_Highlight any areas that you're unsure of, want feedback on, or want reviewers to pay particular attention to._

_Example: I'm not sure I did X correctly, can reviewers please double-check that for me?_

## Metrics

_Is this change something that can or should be tracked? If so, can we do it today? And how? If its easy, do it_

## References

_Add links to any referenced GitHub issues, Zendesk tickets, Jira tickets, Slack threads, etc._

_Example:_

- _[ANE-123](https://fossa.atlassian.net/browse/ANE-123): Implement X._

## Checklist

- [ ] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).

2023-09-06 20:32 UTC, csasarak requested changes
This looks good, I added a comment about how we output error text and suggested some ideas for changing it. If they aren't workable let me know and I can approve.

2023-09-06 23:30 UTC, spatten commented on src/App/Fossa/Analyze.hs
> +    NoneDiscovered -> fatalWithKeywordSearchExplanation (maybe False (not . null . lernieResultsKeywordSearches) lernieResults) ErrNoProjectsDiscovered
You're right, no need to output the warning and the error. I've fixed this now

2023-09-06 23:31 UTC, spatten commented on src/App/Fossa/Analyze.hs
> +        , "This will result in exiting with an error."
I think it's fine to leave it with the standard error code for now. We will fix this properly in https://fossa.atlassian.net/browse/ANE-1175

2023-09-07 19:32 UTC, csasarak commented
I like the new error output, thanks for doing that! 
<img width="1182" alt="Screenshot 2023-09-07 at 3 31 58 PM" src="https://github.com/fossas/fossa-cli/assets/190980/3285c350-4302-47ba-89dd-ed525450190e">

2023-09-07 19:34 UTC, csasarak approved these changes

2023-09-08 19:33 UTC, merged