NuGet strategy consolidation
fossas/fossa-cli pull request #1461
Opened 2024-08-21 00:59 UTC by JeffreyHuynh1

# Overview

_Provide an overview of this change. Describe the intent of this change, and how it implements that intent._

_Example: This PR accomplishes X by doing Y._

## Acceptance criteria

_If this PR is successful, what impact does it have on the user experience?_

_Example: When users do X, Y should now happen._

## Testing plan

_How did you validate that this PR works? What literal steps did you take when manually checking that your code works?_

_Example:_

1. _Set up test case X._
2. _Run command Y. Make sure Z happens._

_This section should list concrete steps that a reviewer can sanity check and repeat on their own machine (and provide any needed test cases)._

## Risks

_Highlight any areas that you're unsure of, want feedback on, or want reviewers to pay particular attention to._

_Example: I'm not sure I did X correctly, can reviewers please double-check that for me?_

## Metrics

_Is this change something that can or should be tracked? If so, can we do it today? And how? If its easy, do it_

## References

_Add links to any referenced GitHub issues, Zendesk tickets, Jira tickets, Slack threads, etc._

_Example:_

- _[ANE-123](https://fossa.atlassian.net/browse/ANE-123): Implement X._

## Checklist

- [ ] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] If this PR added docs, I added links as appropriate to the user manual's ToC in `docs/README.ms` and gave consideration to how discoverable or not my documentation is.
- [ ] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json` AND I have updated example files used by `fossa init` command. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).
- [ ] If I made changes to a subcommand's options, I updated `docs/references/subcommands/<subcommand>.md`.

2024-08-31 00:05 UTC, spatten requested changes
I think we need some tests that test the new behaviour works and actually runs the correct strategy depending on whether a `project.assets.json` file or a `.csproj` file is found during discovery.

We should have a test plan that tests these two cases as well, so we can manually validate that this works.

2024-08-31 00:05 UTC, spatten commented on src/Strategy/NuGet.hs
> +import Strategy.NuGet.PackageReference qualified as ProjectAssetsJson
You're importing the same package twice but calling it different things. Shouldn't the second one of these be imported from `Strategy.NuGet.ProjectAssetsJson`?

2024-08-31 00:05 UTC, spatten commented on src/Strategy/NuGet.hs
> +getDeps project = context "NuGet" (getAssetsJsonDeps project <||> getPackageReferenceDeps project)
It feels weird that we're just running `getAssetsJsonDeps` on the file even if it's not named `project.assets.json`. Should we switch on the filename, or add a new field to the `Nuget` type that tells us which type of analysis we should be doing?

2025-01-08 20:43 UTC, james-fossa commented on src/Strategy/NuGet.hs
> +import Strategy.NuGet.PackageReference qualified as ProjectAssetsJson
I've picked this up and am working from the assumption that this was a typo and meant to be `Strategy.NuGet.ProjectAssetsJson`

2025-01-09 22:01 UTC, james-fossa commented on src/Strategy/NuGet.hs
> +getDeps project = context "NuGet" (getAssetsJsonDeps project <||> getPackageReferenceDeps project)
I changed this to call `getAssetsJsonDeps` only on `project.assets.json`. I think that we should probably rely on the file in question living where it does to avoid some perverse edge case like "this other JSON file I found is a valid `project.assets.json` file but dotnet will not treat it as such. I hold this opinion lightly, will revert if desired.

2025-01-09 22:02 UTC, james-fossa commented on docs/references/strategies/languages/dotnet/nuget.md
> +| Strategy                                 | Direct Deps | Transitive Deps | Edges |
Thanks for the extension link; done and done

2025-01-09 22:02 UTC, james-fossa commented on docs/features/manual-dependencies.md
>  - `cran` - Dependencies located on the [CRAN](https://cran.r-project.org/) like repository.
Not knowing a reason to re-enable, I've added these back

2025-01-20 18:59 UTC, spatten approved these changes
This looks great! I had a few, minor and optional, nits. Nothing blocking approval

2025-01-20 18:59 UTC, spatten commented on docs/features/manual-dependencies.md
> +<!-- markdown-link-check-disable-next-line -->
Okay, now I'm reversing my previous comment. This comment is not on current master, and I don't think this PR should change that

2025-01-20 18:59 UTC, spatten commented on docs/references/strategies/languages/dotnet/nuget-qr.md
> +# Quick reference: NuGet
This file is new in this PR and not referenced anywhere in the documentation. There are other `<language>-qr.md` files in the repo, but I think it's confusing to have both `nuget.md` and `nuget-qr.md`. 

So, I know you didn't add it, but I think we should delete it

2025-01-20 18:59 UTC, spatten commented on integration-test/Analysis/NugetSpec.hs
> +testDotnetCoreTwoExampleForPackageAssetsJson :: Spec
Should this be named `testDotnetCoreTwoExampleForProjectAssetsJson`?

2025-02-14 15:02 UTC, merged